/**
 * Turning a model id into the human-readable name that goes in the signature.
 *
 * The map below is deliberately historical: old ids keep rendering the name
 * they had, so a signature written last year still reads the way it did.
 */

/**
 * Format model name to human-readable form
 */
export function formatModelName(model: { providerID: string; modelID: string } | string | undefined): string {
  if (!model) return "Unknown Model";

  // If model is a string
  if (typeof model === "string") {
    return formatModelString(model);
  }

  // If model is an object with providerID and modelID
  if (typeof model === "object") {
    if (model.modelID) {
      return formatModelString(model.modelID);
    }
  }

  return "Unknown Model";
}

/**
 * Format model ID string
 */
function formatModelString(modelId: string): string {
  if (!modelId) return "Unknown Model";

  // Remove dates and hashes from name
  const cleanName = modelId
    .replace(/-\d{4}-\d{2}-\d{2}/g, "") // Remove dates
    .replace(/-[a-f0-9]{7,}/g, "") // Remove short hashes
    .replace(/@/g, "/"); // Replace @ with /

  // Known models - use nice names
  const knownModels: Record<string, string> = {
    // Kimi / Moonshot models
    kimi: "Kimi",
    "kimi-latest": "Kimi",
    "kimi-for-coding": "Kimi",
    "kimi-thinking-preview": "Kimi",
    "kimi-k2": "Kimi K2",
    "kimi-k2-turbo-preview": "Kimi K2",
    "kimi-k2-thinking": "Kimi K2 Thinking",
    "kimi-k2-thinking-turbo": "Kimi K2 Thinking",
    "kimi-k2.5": "Kimi K2.5",
    k2p5: "Kimi K2.5",
    "moonshot-v1": "Moonshot",
    "moonshot-v1-8k": "Moonshot",
    "moonshot-v1-32k": "Moonshot",
    "moonshot-v1-128k": "Moonshot",
    "moonshot-v1-vision-preview": "Moonshot Vision",
    "moonshot-v1-8k-vision-preview": "Moonshot Vision",
    "moonshot-v1-32k-vision-preview": "Moonshot Vision",
    "moonshot-v1-128k-vision-preview": "Moonshot Vision",
    "kimi-k2.6": "Kimi K2.6",
    "kimi-k2-6": "Kimi K2.6",
    "kimi-k2.7-code": "Kimi K2.7 Code",

    // Claude models (Anthropic)
    claude: "Claude",
    "claude-3": "Claude 3",
    "claude-3-opus": "Claude 3 Opus",
    "claude-3-sonnet": "Claude 3 Sonnet",
    "claude-3-haiku": "Claude 3 Haiku",
    "claude-3-5-sonnet": "Claude 3.5 Sonnet",
    "claude-3-5-haiku": "Claude 3.5 Haiku",
    "claude-3-7-sonnet": "Claude 3.7 Sonnet",
    "claude-sonnet-4": "Claude Sonnet 4",
    "claude-opus-4": "Claude Opus 4",
    "claude-opus-4-1": "Claude Opus 4.1",
    "claude-sonnet-4-5": "Claude Sonnet 4.5",
    "claude-haiku-4-5": "Claude Haiku 4.5",
    "claude-opus-4-5": "Claude Opus 4.5",
    "claude-opus-4-6": "Claude Opus 4.6",
    "claude-sonnet-4-6": "Claude Sonnet 4.6",
    "claude-opus-4-7": "Claude Opus 4.7",
    "claude-opus-4-8": "Claude Opus 4.8",
    "claude-fable-5": "Claude Fable 5",
    "claude-mythos-5": "Claude Mythos 5",

    // GPT models (OpenAI)
    "gpt-4": "GPT-4",
    "gpt-4-turbo": "GPT-4 Turbo",
    "gpt-4o": "GPT-4o",
    "gpt-4o-mini": "GPT-4o Mini",
    "gpt-4-1": "GPT-4.1",
    "gpt-4-1-mini": "GPT-4.1 Mini",
    "gpt-4-1-nano": "GPT-4.1 Nano",
    "gpt-4-5": "GPT-4.5",
    "gpt-4-5-preview": "GPT-4.5 Preview",
    "gpt-5": "GPT-5",
    "gpt-5-chat": "GPT-5",
    "gpt-5-mini": "GPT-5 Mini",
    "gpt-5-nano": "GPT-5 Nano",
    "gpt-5-pro": "GPT-5 Pro",
    "gpt-5-1": "GPT-5.1",
    "gpt-5-2": "GPT-5.2",
    "gpt-5-2-pro": "GPT-5.2 Pro",
    "gpt-5-3": "GPT-5.3",
    "gpt-5.3": "GPT-5.3",
    "gpt-5-4": "GPT-5.4",
    "gpt-5.4": "GPT-5.4",
    "gpt-5-4-pro": "GPT-5.4 Pro",
    "gpt-5.4-pro": "GPT-5.4 Pro",
    "gpt-5-4-mini": "GPT-5.4 Mini",
    "gpt-5.4-mini": "GPT-5.4 Mini",
    "gpt-5-4-nano": "GPT-5.4 Nano",
    "gpt-5.4-nano": "GPT-5.4 Nano",
    "gpt-5-5": "GPT-5.5",
    "gpt-5.5": "GPT-5.5",
    "gpt-5-5-pro": "GPT-5.5 Pro",
    "gpt-5.5-pro": "GPT-5.5 Pro",

    // Codex models (OpenAI)
    "codex-1": "Codex",
    "codex-mini": "Codex Mini",
    "gpt-5-codex": "GPT-5 Codex",
    "gpt-5.1-codex": "GPT-5.1 Codex",
    "gpt-5-1-codex": "GPT-5.1 Codex",
    "gpt-5.1-codex-mini": "GPT-5.1 Codex Mini",
    "gpt-5-1-codex-mini": "GPT-5.1 Codex Mini",
    "gpt-5.1-codex-max": "GPT-5.1 Codex Max",
    "gpt-5-1-codex-max": "GPT-5.1 Codex Max",
    "gpt-5.2-codex": "GPT-5.2 Codex",
    "gpt-5-2-codex": "GPT-5.2 Codex",
    "gpt-5.3-codex": "GPT-5.3 Codex",
    "gpt-5-3-codex": "GPT-5.3 Codex",
    "gpt-5.3-codex-spark": "GPT-5.3 Codex Spark",
    "gpt-5-3-codex-spark": "GPT-5.3 Codex Spark",

    // o-series reasoning models (OpenAI)
    "o1": "o1",
    "o1-mini": "o1 Mini",
    "o1-preview": "o1 Preview",
    "o1-pro": "o1 Pro",
    "o3": "o3",
    "o3-mini": "o3 Mini",
    "o3-pro": "o3 Pro",
    "o3-deep-research": "o3 Deep Research",
    "o4-mini": "o4 Mini",
    "o4-mini-deep-research": "o4 Mini Deep Research",

    // Gemini models (Google)
    gemini: "Gemini",
    "gemini-pro": "Gemini Pro",
    "gemini-ultra": "Gemini Ultra",
    "gemini-1-5-pro": "Gemini 1.5 Pro",
    "gemini-1-5-flash": "Gemini 1.5 Flash",
    "gemini-1-5-flash-8b": "Gemini 1.5 Flash 8B",
    "gemini-2-0-pro": "Gemini 2.0 Pro",
    "gemini-2-0-flash": "Gemini 2.0 Flash",
    "gemini-2-0-flash-lite": "Gemini 2.0 Flash Lite",
    "gemini-2-5-pro": "Gemini 2.5 Pro",
    "gemini-2-5-pro-preview": "Gemini 2.5 Pro",
    "gemini-2-5-flash": "Gemini 2.5 Flash",
    "gemini-2-5-flash-lite": "Gemini 2.5 Flash Lite",
    "gemini-3-pro": "Gemini 3 Pro",
    "gemini-3-pro-preview": "Gemini 3 Pro",
    "gemini-3-flash": "Gemini 3 Flash",
    "gemini-3-flash-preview": "Gemini 3 Flash",
    "gemini-3-1-pro": "Gemini 3.1 Pro",
    "gemini-3-1-pro-preview": "Gemini 3.1 Pro",
    "gemini-3-1-flash-lite": "Gemini 3.1 Flash Lite",
    "gemini-3-5-flash": "Gemini 3.5 Flash",
    "gemini-3-5-flash-preview": "Gemini 3.5 Flash",

    // DeepSeek models
    deepseek: "DeepSeek",
    "deepseek-chat": "DeepSeek Chat",
    "deepseek-coder": "DeepSeek Coder",
    "deepseek-reasoner": "DeepSeek R1",
    "deepseek-v3": "DeepSeek V3",
    "deepseek-v3.1": "DeepSeek V3.1",
    "deepseek-v3.2": "DeepSeek V3.2",
    "deepseek-v3.2-exp": "DeepSeek V3.2",
    "deepseek-r1": "DeepSeek R1",
    "deepseek-r1-lite": "DeepSeek R1 Lite",
    "deepseek-prover-v2": "DeepSeek Prover V2",
    "deepseek-v4": "DeepSeek V4",
    "deepseek-v4-pro": "DeepSeek V4 Pro",
    "deepseek-v4-flash": "DeepSeek V4 Flash",

    // Llama models (Meta)
    llama: "Llama",
    "meta-llama-3": "Llama 3",
    "llama-3": "Llama 3",
    "llama-3-1": "Llama 3.1",
    "llama-3-2": "Llama 3.2",
    "llama-3-3": "Llama 3.3",
    "meta-llama-4": "Llama 4",
    "llama-4": "Llama 4",
    "llama-4-maverick": "Llama 4 Maverick",
    "llama-4-scout": "Llama 4 Scout",
    "llama-4-behemoth": "Llama 4 Behemoth",

    // Mistral models
    mistral: "Mistral",
    "mistral-large": "Mistral Large",
    "mistral-large-2": "Mistral Large 2",
    "mistral-large-latest": "Mistral Large",
    "mistral-medium": "Mistral Medium",
    "mistral-medium-3": "Mistral Medium 3",
    "mistral-small": "Mistral Small",
    "mistral-small-3": "Mistral Small 3",
    "mistral-small-3-1": "Mistral Small 3.1",
    "mistral-small-latest": "Mistral Small",
    "mistral-nemo": "Mistral Nemo",
    "mistral-saba": "Mistral Saba",
    "mistral-ocr": "Mistral OCR",
    codestral: "Codestral",
    "codestral-mamba": "Codestral Mamba",
    "pixtral-large": "Pixtral Large",
    "pixtral-12b": "Pixtral 12B",
    magistral: "Magistral",
    "magistral-medium": "Magistral Medium",
    "magistral-small": "Magistral Small",
    devstral: "Devstral",
    "devstral-small": "Devstral Small",
    "devstral-medium": "Devstral Medium",
    ministral: "Ministral",
    "ministral-3b": "Ministral 3B",
    mathstral: "Mathstral",
    "mistral-large-3": "Mistral Large 3",
    "mistral-medium-3-5": "Mistral Medium 3.5",
    "mistral-small-4": "Mistral Small 4",
    "ministral-3": "Ministral 3",
    "ministral-3-8b": "Ministral 3 8B",
    "mistral-ocr-3": "Mistral OCR 3",
    voxtral: "Voxtral",
    "voxtral-small": "Voxtral Small",

    // Qwen models (Alibaba)
    qwen: "Qwen",
    "qwen-2": "Qwen 2",
    "qwen-2-5": "Qwen 2.5",
    "qwen2-5-coder": "Qwen 2.5 Coder",
    "qwen2-5-math": "Qwen 2.5 Math",
    qwen3: "Qwen 3",
    "qwen3-max": "Qwen 3 Max",
    "qwen3-max-preview": "Qwen 3 Max",
    "qwen3-coder-plus": "Qwen 3 Coder",
    "qwen3-coder-flash": "Qwen 3 Coder",
    "qwen3.5-plus": "Qwen 3.5 Plus",
    "qwen3.5-flash": "Qwen 3.5 Flash",
    "qwen-turbo": "Qwen Turbo",
    "qwen-plus": "Qwen Plus",
    "qwen-max": "Qwen Max",
    "qwen-flash": "Qwen Flash",
    "qwen-long": "Qwen Long",
    "qwen-coder-plus": "Qwen Coder",
    "qwen-coder-turbo": "Qwen Coder",
    "qwen-vl": "Qwen VL",
    "qwen-vl-max": "Qwen VL Max",
    "qwen-vl-plus": "Qwen VL Plus",
    qwq: "QwQ",
    "qwq-plus": "QwQ Plus",
    "qwen3.6-plus": "Qwen 3.6 Plus",
    "qwen3-6-plus": "Qwen 3.6 Plus",
    "qwen3.7-max": "Qwen 3.7 Max",
    "qwen3-7-max": "Qwen 3.7 Max",
    "qwen3.7-plus": "Qwen 3.7 Plus",
    "qwen3-7-plus": "Qwen 3.7 Plus",
    "qwen3-vl-plus": "Qwen 3 VL Plus",
    "qwen3-vl-flash": "Qwen 3 VL Flash",
    "qwen3-vl-max": "Qwen 3 VL Max",
    "qwen-vl-ocr": "Qwen VL OCR",
    "qwen3.6-flash": "Qwen 3.6 Flash",
    "qwen3-6-flash": "Qwen 3.6 Flash",
    "qwen3.6-max": "Qwen 3.6 Max",
    "qwen3-6-max": "Qwen 3.6 Max",
    "qwen3.5-omni-plus": "Qwen 3.5 Omni Plus",
    "qwen3-5-omni-plus": "Qwen 3.5 Omni Plus",
    "qwen3-omni-flash": "Qwen 3 Omni Flash",
    "qwen-omni-turbo": "Qwen Omni Turbo",

    // Grok models (xAI)
    grok: "Grok",
    "grok-2": "Grok 2",
    "grok-2-vision": "Grok 2 Vision",
    "grok-3": "Grok 3",
    "grok-3-beta": "Grok 3",
    "grok-3-fast": "Grok 3",
    "grok-3-fast-beta": "Grok 3",
    "grok-3-mini": "Grok 3 Mini",
    "grok-3-mini-beta": "Grok 3 Mini",
    "grok-3-mini-fast": "Grok 3 Mini",
    "grok-3-mini-fast-beta": "Grok 3 Mini",
    "grok-beta": "Grok 2 Beta",
    "grok-4": "Grok 4",
    "grok-4-heavy": "Grok 4 Heavy",
    "grok-4-fast": "Grok 4 Fast",
    "grok-4-fast-reasoning": "Grok 4 Fast",
    "grok-4-fast-non-reasoning": "Grok 4 Fast",
    "grok-code-fast-1": "Grok Code Fast 1",
    "grok-4.1": "Grok 4.1",
    "grok-4-1": "Grok 4.1",
    "grok-4.1-fast": "Grok 4.1 Fast",
    "grok-4-1-fast": "Grok 4.1 Fast",
    "grok-4.1-fast-reasoning": "Grok 4.1 Fast",
    "grok-4-1-fast-reasoning": "Grok 4.1 Fast",
    "grok-4.1-fast-non-reasoning": "Grok 4.1 Fast",
    "grok-4-1-fast-non-reasoning": "Grok 4.1 Fast",
    "grok-4.20": "Grok 4.20",
    "grok-4-20": "Grok 4.20",
    "grok-4.20-reasoning": "Grok 4.20",
    "grok-4-20-reasoning": "Grok 4.20",
    "grok-4.20-non-reasoning": "Grok 4.20",
    "grok-4-20-non-reasoning": "Grok 4.20",
    "grok-4.3": "Grok 4.3",
    "grok-4-3": "Grok 4.3",

    // Cohere models
    command: "Command",
    "command-r": "Command R",
    "command-r-plus": "Command R+",
    "command-r7b": "Command R7B",
    "command-a": "Command A",

    // Perplexity / Sonar models
    perplexity: "Perplexity",
    sonar: "Sonar",
    "sonar-pro": "Sonar Pro",
    "sonar-reasoning": "Sonar Reasoning",
    "sonar-reasoning-pro": "Sonar Reasoning Pro",
    "sonar-deep-research": "Sonar Deep Research",
    "r1-1776": "R1-1776",

    // Yi models (01.AI)
    "yi-lightning": "Yi Lightning",
    "yi-lightning-lite": "Yi Lightning Lite",
    "yi-large": "Yi Large",
    "yi-large-turbo": "Yi Large Turbo",
    "yi-large-fc": "Yi Large FC",
    "yi-large-rag": "Yi Large RAG",
    "yi-vision": "Yi Vision",
    "yi-medium": "Yi Medium",
    "yi-spark": "Yi Spark",

    // GLM models (Zhipu AI / Z.ai)
    glm: "GLM",
    "glm-5.2": "GLM-5.2",
    "glm-5-2": "GLM-5.2",
    "glm-5.1": "GLM-5.1",
    "glm-5-1": "GLM-5.1",
    "glm-5": "GLM-5",
    "glm-5-turbo": "GLM-5 Turbo",
    "glm-5v-turbo": "GLM-5V Turbo",
    "glm-4.7": "GLM-4.7",
    "glm-4-7": "GLM-4.7",
    "glm-4.7-flash": "GLM-4.7 Flash",
    "glm-4-7-flash": "GLM-4.7 Flash",
    "glm-4.6": "GLM-4.6",
    "glm-4-6": "GLM-4.6",
    "glm-4.6v": "GLM-4.6V",
    "glm-4-6v": "GLM-4.6V",
    "glm-4.5": "GLM-4.5",
    "glm-4-5": "GLM-4.5",
    "glm-4.5-air": "GLM-4.5 Air",
    "glm-4-5-air": "GLM-4.5 Air",
    "glm-4.5-x": "GLM-4.5-X",
    "glm-4-5-x": "GLM-4.5-X",
    "glm-4.5-airx": "GLM-4.5-AirX",
    "glm-4-5-airx": "GLM-4.5-AirX",
    "glm-4.5-flash": "GLM-4.5 Flash",
    "glm-4-5-flash": "GLM-4.5 Flash",
    "glm-4.5v": "GLM-4.5V",
    "glm-4-5v": "GLM-4.5V",
    "glm-4-32b": "GLM-4-32B",
    "glm-4-plus": "GLM-4-Plus",
    "glm-4-air": "GLM-4 Air",
    "glm-4-flashx": "GLM-4-FlashX",
    "glm-z1-air": "GLM-Z1-Air",
    "glm-z1-airx": "GLM-Z1-AirX",
    "glm-z1-flash": "GLM-Z1-Flash",
    "glm-z1-32b": "GLM-Z1-32B",
    "glm-z1-rumination-32b": "GLM-Z1-Rumination-32B",

    // MiniMax models
    minimax: "MiniMax",
    "minimax-m3": "MiniMax M3",
    "minimax-m2.7": "MiniMax M2.7",
    "minimax-m2-7": "MiniMax M2.7",
    "minimax-m2.5": "MiniMax M2.5",
    "minimax-m2-5": "MiniMax M2.5",
    "minimax-m2.1": "MiniMax M2.1",
    "minimax-m2-1": "MiniMax M2.1",
    "minimax-m2": "MiniMax M2",
    "minimax-m1": "MiniMax M1",
    "minimax-text-01": "MiniMax Text-01",
    "minimax-01": "MiniMax-01",
    "abab6.5-chat": "abab6.5",
    "abab6.5s-chat": "abab6.5s",

    // Amazon Nova models
    "nova-2-pro": "Amazon Nova 2 Pro",
    "amazon-nova-2-pro": "Amazon Nova 2 Pro",
    "nova-2-lite": "Amazon Nova 2 Lite",
    "amazon-nova-2-lite": "Amazon Nova 2 Lite",
    "nova-premier": "Amazon Nova Premier",
    "amazon-nova-premier": "Amazon Nova Premier",
    "nova-pro": "Amazon Nova Pro",
    "amazon-nova-pro": "Amazon Nova Pro",
    "nova-lite": "Amazon Nova Lite",
    "amazon-nova-lite": "Amazon Nova Lite",
    "nova-micro": "Amazon Nova Micro",
    "amazon-nova-micro": "Amazon Nova Micro",

    // Baidu ERNIE models
    "ernie-5.1": "ERNIE 5.1",
    "ernie-5-1": "ERNIE 5.1",
    "ernie-5.0": "ERNIE 5.0",
    "ernie-5-0": "ERNIE 5.0",
    "ernie-x1.1": "ERNIE X1.1",
    "ernie-x1-1": "ERNIE X1.1",
    "ernie-x1": "ERNIE X1",
    "ernie-4.5-turbo": "ERNIE 4.5 Turbo",
    "ernie-4-5-turbo": "ERNIE 4.5 Turbo",
    "ernie-4.5": "ERNIE 4.5",
    "ernie-4-5": "ERNIE 4.5",
    "ernie-speed": "ERNIE Speed",
    "ernie-lite": "ERNIE Lite",

    // Tencent Hunyuan models
    "hunyuan-turbos": "Hunyuan TurboS",
    "hunyuan-turbo-s": "Hunyuan TurboS",
    "hunyuan-t1": "Hunyuan T1",
    "hunyuan-a13b": "Hunyuan A13B",
    "hunyuan-standard": "Hunyuan Standard",
    "hunyuan-lite": "Hunyuan Lite",
    "hunyuan-large": "Hunyuan Large",

    // ByteDance Doubao / Seed models
    "doubao-seed-2.0-pro": "Doubao Seed 2.0 Pro",
    "doubao-seed-2-0-pro": "Doubao Seed 2.0 Pro",
    "doubao-seed-2.0-lite": "Doubao Seed 2.0 Lite",
    "doubao-seed-2-0-lite": "Doubao Seed 2.0 Lite",
    "doubao-seed-1.6": "Doubao Seed 1.6",
    "doubao-seed-1-6": "Doubao Seed 1.6",
    "doubao-1.5-pro": "Doubao 1.5 Pro",
    "doubao-1-5-pro": "Doubao 1.5 Pro",
    "doubao-1.5-lite": "Doubao 1.5 Lite",

    // Microsoft Phi models
    "phi-4-reasoning-vision": "Phi-4 Reasoning Vision",
    "phi-4-reasoning-plus": "Phi-4 Reasoning Plus",
    "phi-4-reasoning": "Phi-4 Reasoning",
    "phi-4-mini-reasoning": "Phi-4 Mini Reasoning",
    "phi-4-multimodal": "Phi-4 Multimodal",
    "phi-4-mini": "Phi-4 Mini",
    "phi-4": "Phi-4",
    "phi-3.5-mini": "Phi-3.5 Mini",
    "phi-3-5-mini": "Phi-3.5 Mini",

    // AI21 Jamba models
    "jamba-large-1.7": "Jamba Large 1.7",
    "jamba-large-1-7": "Jamba Large 1.7",
    "jamba-large": "Jamba Large",
    "jamba-mini-2": "Jamba Mini 2",
    "jamba-mini": "Jamba Mini",
    "jamba-3b-2": "Jamba 3B 2",

    // Reka models
    "reka-core": "Reka Core",
    "reka-flash-3.1": "Reka Flash 3.1",
    "reka-flash-3-1": "Reka Flash 3.1",
    "reka-flash-3": "Reka Flash 3",
    "reka-flash": "Reka Flash",
    "reka-edge": "Reka Edge",

    // Anthropic — Claude 5 generation
    "claude-opus-5": "Claude Opus 5",
    "claude-opus-5-fast": "Claude Opus 5 Fast",
    "claude-sonnet-5": "Claude Sonnet 5",
    "claude-mythos-preview": "Claude Mythos Preview",
    "claude-opus-4.8-fast": "Claude Opus 4.8 Fast",
    "claude-opus-4-8-fast": "Claude Opus 4.8 Fast",
    "claude-opus-4.7-fast": "Claude Opus 4.7 Fast",
    "claude-opus-4-7-fast": "Claude Opus 4.7 Fast",
    // Dotted spellings, as served by aggregators
    "claude-opus-4.8": "Claude Opus 4.8",
    "claude-opus-4.7": "Claude Opus 4.7",
    "claude-opus-4.6": "Claude Opus 4.6",
    "claude-opus-4.5": "Claude Opus 4.5",
    "claude-opus-4.1": "Claude Opus 4.1",
    "claude-sonnet-4.6": "Claude Sonnet 4.6",
    "claude-sonnet-4.5": "Claude Sonnet 4.5",
    "claude-haiku-4.5": "Claude Haiku 4.5",

    // OpenAI — GPT-5.6 generation
    "gpt-5.6-sol-pro": "GPT-5.6 Sol Pro",
    "gpt-5-6-sol-pro": "GPT-5.6 Sol Pro",
    "gpt-5.6-sol": "GPT-5.6 Sol",
    "gpt-5-6-sol": "GPT-5.6 Sol",
    "gpt-5.6-terra-pro": "GPT-5.6 Terra Pro",
    "gpt-5-6-terra-pro": "GPT-5.6 Terra Pro",
    "gpt-5.6-terra": "GPT-5.6 Terra",
    "gpt-5-6-terra": "GPT-5.6 Terra",
    "gpt-5.6-luna-pro": "GPT-5.6 Luna Pro",
    "gpt-5-6-luna-pro": "GPT-5.6 Luna Pro",
    "gpt-5.6-luna": "GPT-5.6 Luna",
    "gpt-5-6-luna": "GPT-5.6 Luna",
    "gpt-5.6": "GPT-5.6",
    "gpt-5-6": "GPT-5.6",
    "gpt-5.3-chat": "GPT-5.3 Chat",
    "gpt-5-3-chat": "GPT-5.3 Chat",
    "gpt-5.2-chat": "GPT-5.2 Chat",
    "gpt-5-2-chat": "GPT-5.2 Chat",
    "gpt-chat-latest": "GPT Chat Latest",
    // OpenAI open-weight models
    "gpt-oss-safeguard-20b": "GPT-OSS Safeguard 20B",
    "gpt-oss-120b": "GPT-OSS 120B",
    "gpt-oss-20b": "GPT-OSS 20B",
    "gpt-oss": "GPT-OSS",
    "o4-mini-high": "o4 Mini High",
    "o3-mini-high": "o3 Mini High",

    // Google — Gemini 3.6 and the Gemma open family
    "gemini-3.6-flash": "Gemini 3.6 Flash",
    "gemini-3-6-flash": "Gemini 3.6 Flash",
    "gemini-3.5-flash-lite": "Gemini 3.5 Flash Lite",
    "gemini-3-5-flash-lite": "Gemini 3.5 Flash Lite",
    "gemini-omni-flash": "Gemini Omni Flash",
    "gemini-3.1-flash-lite-preview": "Gemini 3.1 Flash Lite Preview",
    "gemini-3.1-pro-preview-customtools": "Gemini 3.1 Pro Custom Tools",
    "gemma-4-31b-it": "Gemma 4 31B",
    "gemma-4-26b-a4b-it": "Gemma 4 26B A4B",
    "gemma-4": "Gemma 4",
    "gemma-3n-e4b-it": "Gemma 3n 4B",
    "gemma-3-27b-it": "Gemma 3 27B",
    "gemma-3-12b-it": "Gemma 3 12B",
    "gemma-3-4b-it": "Gemma 3 4B",
    "gemma-3": "Gemma 3",
    "gemma-2-27b-it": "Gemma 2 27B",
    "gemma-2": "Gemma 2",
    gemma: "Gemma",

    // xAI — Grok 4.5 and the agentic Grok Build line
    "grok-4.5": "Grok 4.5",
    "grok-4-5": "Grok 4.5",
    "grok-build-0.1": "Grok Build 0.1",
    "grok-build-0-1": "Grok Build 0.1",
    "grok-build": "Grok Build",
    "grok-4.20-multi-agent": "Grok 4.20 Multi-Agent",
    "grok-4-20-multi-agent": "Grok 4.20 Multi-Agent",

    // Meta — the non-Llama Muse Spark line
    "muse-spark-1.2": "Muse Spark 1.2",
    "muse-spark-1-2": "Muse Spark 1.2",
    "muse-spark-1.1": "Muse Spark 1.1",
    "muse-spark-1-1": "Muse Spark 1.1",
    "muse-spark": "Muse Spark",
    "llama-guard-4": "Llama Guard 4",

    // Tencent — the Hunyuan line was renamed to Hy3
    "hy3-preview": "Hunyuan Hy3 Preview",
    hy3: "Hunyuan Hy3",
    "hunyuan-a13b-instruct": "Hunyuan A13B",

    // Alibaba Qwen — 3.5 through 3.8
    "qwen3.8-max": "Qwen3.8 Max",
    "qwen3-8-max": "Qwen3.8 Max",
    "qwen3.7-flash": "Qwen3.7 Flash",
    "qwen3-7-flash": "Qwen3.7 Flash",
    "qwen3.6-max-preview": "Qwen3.6 Max Preview",
    "qwen3.6-35b-a3b": "Qwen3.6 35B A3B",
    "qwen3.6-27b": "Qwen3.6 27B",
    "qwen3-6-27b": "Qwen3.6 27B",
    "qwen3.5-397b-a17b": "Qwen3.5 397B A17B",
    "qwen3.5-122b-a10b": "Qwen3.5 122B A10B",
    "qwen3.5-35b-a3b": "Qwen3.5 35B A3B",
    "qwen3.5-27b": "Qwen3.5 27B",
    "qwen3.5-9b": "Qwen3.5 9B",
    "qwen3-coder-next": "Qwen3 Coder Next",
    "qwen3-max-thinking": "Qwen3 Max Thinking",
    "qwen3-next-80b-a3b-thinking": "Qwen3 Next 80B A3B Thinking",
    "qwen3-next-80b-a3b-instruct": "Qwen3 Next 80B A3B",
    "qwen3-next": "Qwen3 Next",
    "qwen3-235b-a22b-thinking-2507": "Qwen3 235B A22B Thinking",
    "qwen3-235b-a22b": "Qwen3 235B A22B",
    "qwen3-30b-a3b-thinking-2507": "Qwen3 30B A3B Thinking",
    "qwen3-30b-a3b": "Qwen3 30B A3B",
    "qwen3-32b": "Qwen3 32B",
    "qwen3-14b": "Qwen3 14B",
    "qwen3-8b": "Qwen3 8B",
    "qwen3-coder-30b-a3b-instruct": "Qwen3 Coder 30B A3B",
    "qwen3-coder": "Qwen3 Coder",
    "qwen3-vl-235b-a22b-thinking": "Qwen3 VL 235B A22B Thinking",
    "qwen3-vl-235b-a22b-instruct": "Qwen3 VL 235B A22B",
    "qwen3-vl-30b-a3b-thinking": "Qwen3 VL 30B A3B Thinking",
    "qwen3-vl-30b-a3b-instruct": "Qwen3 VL 30B A3B",
    "qwen3-vl-32b-instruct": "Qwen3 VL 32B",
    "qwen3-vl-8b-thinking": "Qwen3 VL 8B Thinking",
    "qwen3-vl-8b-instruct": "Qwen3 VL 8B",
    "qwen2.5-vl-72b-instruct": "Qwen2.5 VL 72B",
    "qwen-2.5-coder-32b-instruct": "Qwen2.5 Coder 32B",
    "qwen-2.5-72b-instruct": "Qwen2.5 72B",
    "qwen-2.5-7b-instruct": "Qwen2.5 7B",

    // Moonshot
    "kimi-k3": "Kimi K3",
    "kimi-k2-0905": "Kimi K2",
    "kimi-for-coding-highspeed": "Kimi for Coding",

    // DeepSeek — dated builds and older lines
    "deepseek-v4-flash-0731": "DeepSeek V4 Flash",
    "deepseek-v3.1-terminus": "DeepSeek V3.1 Terminus",
    "deepseek-chat-v3.1": "DeepSeek V3.1",
    "deepseek-chat-v3-0324": "DeepSeek V3",
    "deepseek-r1-distill-llama-70b": "DeepSeek R1 Distill Llama 70B",
    "deepseek-r1-0528": "DeepSeek R1",

    // Z.ai GLM — flash tiers
    "glm-4.7-flashx": "GLM-4.7 FlashX",
    "glm-4-7-flashx": "GLM-4.7 FlashX",
    "glm-4.6v-flashx": "GLM-4.6V FlashX",
    "glm-4-6v-flashx": "GLM-4.6V FlashX",
    "glm-4.6v-flash": "GLM-4.6V Flash",
    "glm-4-6v-flash": "GLM-4.6V Flash",

    // MiniMax
    "minimax-m2.7-highspeed": "MiniMax M2.7",
    "minimax-m2-7-highspeed": "MiniMax M2.7",
    "minimax-m2.5-highspeed": "MiniMax M2.5",
    "minimax-m2-5-highspeed": "MiniMax M2.5",
    "minimax-m2.1-highspeed": "MiniMax M2.1",
    "minimax-m2-1-highspeed": "MiniMax M2.1",
    "minimax-m2-her": "MiniMax M2-her",

    // ByteDance Seed
    "seed-2.0-lite": "Seed 2.0 Lite",
    "seed-2-0-lite": "Seed 2.0 Lite",
    "seed-2.0-mini": "Seed 2.0 Mini",
    "seed-2-0-mini": "Seed 2.0 Mini",
    "seed-1.6-flash": "Seed 1.6 Flash",
    "seed-1.6": "Seed 1.6",
    "seed-oss-36b-instruct": "Seed OSS 36B",
    "ui-tars-1.5-7b": "UI-TARS 7B",
    "ui-tars": "UI-TARS",

    // NVIDIA Nemotron
    "nemotron-3-ultra-550b-a55b": "Nemotron 3 Ultra",
    "nemotron-3-super-120b-a12b": "Nemotron 3 Super",
    "nemotron-3-nano-omni-30b-a3b-reasoning": "Nemotron 3 Nano Omni",
    "nemotron-3-nano-30b-a3b": "Nemotron 3 Nano",
    "nemotron-3-ultra": "Nemotron 3 Ultra",
    "nemotron-3-super": "Nemotron 3 Super",
    "nemotron-3-nano": "Nemotron 3 Nano",
    "nemotron-nano-12b-v2-vl": "Nemotron Nano 12B V2 VL",
    "nemotron-nano-9b-v2": "Nemotron Nano 9B V2",
    "nemotron-nano": "Nemotron Nano",
    "nemotron-super": "Nemotron Super",
    "nemotron-ultra": "Nemotron Ultra",
    nemotron: "Nemotron",

    // Mistral — the dated ids its API actually expects
    "mistral-large-2512": "Mistral Large 3",
    "mistral-large-2407": "Mistral Large 2",
    "mistral-small-2603": "Mistral Small 4",
    "mistral-small-3.2-24b-instruct": "Mistral Small 3.2",
    "mistral-small-3.1-24b-instruct": "Mistral Small 3.1",
    "mistral-small-24b-instruct-2501": "Mistral Small 3",
    "mistral-medium-3.1": "Mistral Medium 3.1",
    "mistral-ocr-4-0": "Mistral OCR 4",
    "mistral-ocr-2512": "Mistral OCR 3",
    "ministral-14b-2512": "Ministral 3 14B",
    "ministral-8b-2512": "Ministral 3 8B",
    "ministral-3b-2512": "Ministral 3 3B",
    "mixtral-8x22b-instruct": "Mixtral 8x22B",
    "codestral-2508": "Codestral 25.08",
    "devstral-2-25-12": "Devstral 2",
    "labs-leanstral-1-5": "Leanstral 1.5",
    "voxtral-small-24b-2507": "Voxtral Small 24B",

    // Cohere
    "command-a-plus": "Command A+",
    "command-a-reasoning": "Command A Reasoning",
    "command-a-translate": "Command A Translate",
    "command-a-vision": "Command A Vision",
    "command-r-plus-08-2024": "Command R+",
    "command-r-08-2024": "Command R",
    "command-r7b-12-2024": "Command R7B",
    "north-mini-code": "North Mini Code",
    "tiny-aya": "Tiny Aya",

    // Amazon Nova — the Bedrock id spellings
    "nova-2-lite-v1": "Nova 2 Lite",
    "nova-premier-v1": "Nova Premier",
    "nova-pro-v1": "Nova Pro",
    "nova-lite-v1": "Nova Lite",
    "nova-micro-v1": "Nova Micro",
    "nova-2-sonic": "Nova 2 Sonic",

    // Coding-tool vendors
    "composer-2.5": "Composer 2.5",
    "composer-2-5": "Composer 2.5",
    "composer-2": "Composer 2",
    composer: "Composer",
    "swe-1-7-lightning": "SWE-1.7 Lightning",
    "swe-1-7": "SWE-1.7",
    "swe-1-6": "SWE-1.6",
    "swe-1": "SWE-1",
    "laguna-s-2.1": "Laguna S 2.1",
    "laguna-s-2-1": "Laguna S 2.1",
    "laguna-xs-2.1": "Laguna XS 2.1",
    "laguna-xs-2-1": "Laguna XS 2.1",
    laguna: "Laguna",
    "kat-coder-pro-v2.5": "KAT-Coder Pro V2.5",
    "kat-coder-pro-v2-5": "KAT-Coder Pro V2.5",
    "kat-coder-air-v2.5": "KAT-Coder Air V2.5",
    "kat-coder-air-v2-5": "KAT-Coder Air V2.5",
    "kat-coder-pro-v2": "KAT-Coder Pro V2",
    "kat-coder-v2.5-dev": "KAT-Coder V2.5 Dev",
    "kat-coder": "KAT-Coder",
    "kat-dev": "KAT-Dev",
    "mercury-coder": "Mercury Coder",
    "mercury-2": "Mercury 2",
    mercury: "Mercury",
    mellum2: "Mellum2",
    mellum: "Mellum",
    "zeta-2.1": "Zeta 2.1",
    "zeta-2-1": "Zeta 2.1",
    "morph-v3-large": "Morph V3 Large",
    "morph-v3-fast": "Morph V3 Fast",
    "relace-apply-3": "Relace Apply 3",
    "relace-search": "Relace Search",

    // Thinking Machines
    "inkling-small": "Inkling Small",
    inkling: "Inkling",

    // Meituan
    "longcat-2.0": "LongCat 2.0",
    "longcat-2-0": "LongCat 2.0",
    "longcat-flash-chat": "LongCat Flash",
    longcat: "LongCat",

    // Ant Group
    "ling-3.0-flash": "Ling 3.0 Flash",
    "ling-3-0-flash": "Ling 3.0 Flash",
    "ling-3.0-tiny": "Ling 3.0 Tiny",
    "ling-3.0": "Ling 3.0",
    "ling-2.6-flash": "Ling 2.6 Flash",
    "ling-2.6-1t": "Ling 2.6 1T",
    "ring-2.6-1t": "Ring 2.6 1T",
    ling: "Ling",

    // Xiaomi
    "mimo-v2.5-pro": "MiMo V2.5 Pro",
    "mimo-v2-5-pro": "MiMo V2.5 Pro",
    "mimo-v2.5": "MiMo V2.5",
    "mimo-v2-5": "MiMo V2.5",
    "mimo-v2-flash": "MiMo V2 Flash",
    mimo: "MiMo",

    // StepFun
    "step-3.7-flash": "Step 3.7 Flash",
    "step-3-7-flash": "Step 3.7 Flash",
    "step-3.5-flash": "Step 3.5 Flash",
    "step-3-5-flash": "Step 3.5 Flash",
    "step-3": "Step 3",

    // Xiaomi, InternLM, Tele-AI, Baichuan
    "intern-s2": "Intern-S2",
    "intern-s1": "Intern-S1",
    "telechat3": "TeleChat3",
    "telechat2": "TeleChat2",
    "baichuan-m3": "Baichuan M3",
    "baichuan-m2": "Baichuan M2",
    baichuan4: "Baichuan 4",
    baichuan3: "Baichuan 3",
    baichuan: "Baichuan",

    // Naver HyperCLOVA X
    "hcx-dash-002": "HyperCLOVA X Dash 002",
    "hcx-dash-001": "HyperCLOVA X Dash 001",
    "hcx-007": "HyperCLOVA X 007",
    "hcx-005": "HyperCLOVA X 005",
    "hcx-003": "HyperCLOVA X 003",
    "hyperclovax-seed-think": "HyperCLOVA X SEED Think",
    hyperclovax: "HyperCLOVA X",

    // LG EXAONE
    "k-exaone-2.0": "K-EXAONE 2.0",
    "k-exaone-2-0": "K-EXAONE 2.0",
    "k-exaone": "K-EXAONE",
    "exaone-4.5": "EXAONE 4.5",
    "exaone-4-5": "EXAONE 4.5",
    "exaone-4.0": "EXAONE 4.0",
    "exaone-4-0": "EXAONE 4.0",
    exaone: "EXAONE",

    // Upstage, Sarvam, SK Telecom, KT
    "solar-pro-3": "Solar Pro 3",
    "solar-open2": "Solar Open 2",
    "solar-open": "Solar Open",
    "solar-pro": "Solar Pro",
    "sarvam-105b": "Sarvam 105B",
    "sarvam-30b": "Sarvam 30B",
    "sarvam-m": "Sarvam-M",
    "a.x-k2": "A.X-K2",
    "mi-dm-k-2-5-pro": "Mi:dm K-2.5 Pro",

    // iFlytek Spark — the API selects a version by this string
    "spark-x": "Spark X",
    "4.0ultra": "Spark 4.0 Ultra",
    "generalv3.5": "Spark Max",
    generalv3: "Spark Pro",

    // Allen AI, IBM, Nous Research
    "olmo-3-32b-think": "OLMo 3 32B Think",
    "olmo-3-think": "OLMo 3 Think",
    "olmo-3": "OLMo 3",
    olmo: "OLMo",
    "granite-4.1-8b": "Granite 4.1 8B",
    "granite-4.1": "Granite 4.1",
    "granite-4-1": "Granite 4.1",
    "granite-4.0-h-micro": "Granite 4.0 Micro",
    "granite-4.0": "Granite 4.0",
    granite: "Granite",
    "hermes-4-405b": "Hermes 4 405B",
    "hermes-4-70b": "Hermes 4 70B",
    "hermes-4.3": "Hermes 4.3",
    "hermes-4": "Hermes 4",
    "hermes-3-llama-3.1-405b": "Hermes 3 405B",
    "hermes-3-llama-3.1-70b": "Hermes 3 70B",
    "hermes-3": "Hermes 3",
    hermes: "Hermes",
    "nomos-1": "Nomos 1",
    nouscoder: "NousCoder",

    // Smaller and newer labs
    "aion-3.0-mini": "Aion 3.0 Mini",
    "aion-3.0": "Aion 3.0",
    "aion-2.0": "Aion 2.0",
    "aion-rp-llama-3.1-8b": "Aion-RP 8B",
    "nex-n2-pro": "Nex-N2 Pro",
    "nex-n2-mini": "Nex-N2 Mini",
    "fugu-ultra": "Fugu Ultra",
    fugu: "Fugu",
    "cogito-v2.1-671b": "Cogito v2.1 671B",
    cogito: "Cogito",
    "trinity-large-thinking": "Trinity Large Thinking",
    "trinity-large": "Trinity Large",
    "virtuoso-large": "Virtuoso Large",
    "palmyra-x5": "Palmyra X5",
    palmyra: "Palmyra",
    "perceptron-mk1": "Perceptron Mk1",
    "intellect-3": "INTELLECT-3",
    "lfm2.5": "LFM2.5",
    "instella-moe": "Instella MoE",
    "apertus-70b-instruct": "Apertus 70B",
    "apertus-8b-instruct": "Apertus 8B",
    apertus: "Apertus",
    "minicpm5": "MiniCPM 5",
    "sonar-pro-search": "Sonar Pro Search",
    "rakuten-ai-3.0": "Rakuten AI 3.0",
    "typhoon-2": "Typhoon 2",
    "apriel-1.6-15b-thinker": "Apriel 1.6 15B Thinker",
    "marin-8b-instruct": "Marin 8B",
    "falcon-h1r": "Falcon H1R",
    "falcon-h1": "Falcon H1",
    falcon: "Falcon",

    // Community fine-tunes served by aggregators
    "dolphin-mistral-24b-venice-edition": "Dolphin Mistral 24B Venice",
    "l3.3-euryale-70b": "Llama 3.3 Euryale 70B",
    "l3.1-euryale-70b": "Llama 3.1 Euryale 70B",
    "l3-lunaris-8b": "Llama 3 Lunaris 8B",
    "cydonia-24b-v4.1": "Cydonia 24B v4.1",
    "magnum-v4-72b": "Magnum v4 72B",
    "mythomax-l2-13b": "MythoMax 13B",
    "remm-slerp-l2-13b": "ReMM SLERP 13B",
    "unslopnemo-12b": "UnslopNemo 12B",
    "rocinante-12b": "Rocinante 12B",
    "skyfall-36b-v2": "Skyfall 36B v2",
    "wizardlm-2-8x22b": "WizardLM-2 8x22B",
    weaver: "Weaver",
  };

  // Check exact match
  if (knownModels[cleanName]) {
    return knownModels[cleanName];
  }

  // Check partial match. Try the most specific (longest) keys first so generic
  // keys like "claude" or "gpt-4" don't shadow specific ones like
  // "claude-3-5-sonnet" or "gpt-4o" for unknown model-id variants.
  const lowerName = cleanName.toLowerCase();
  const keysBySpecificity = Object.keys(knownModels).sort((a, b) => b.length - a.length);
  for (const key of keysBySpecificity) {
    if (lowerName.includes(key.toLowerCase())) {
      return knownModels[key];
    }
  }

  // Return as-is with capitalized first letter
  return cleanName.charAt(0).toUpperCase() + cleanName.slice(1);
}
